# Generated by Django 5.0 on 2023-12-29 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_company_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.user')),
            ],
            options={
                'db_table': 'company_users',
            },
        ),
    ]
